data:
  dataset_root: '/home/omega/datasets'
  dataset:
    office:
      network: resnet50 #ResNet50
      is_center: False
      num_classes: 31
      bottleneck_dim: 1024
      iterations_per_epoch: 10

    office-home:
      network: resnet50 #ResNet50
      is_center: False  # True
      num_classes: 65
      bottleneck_dim: 2048
      iterations_per_epoch: 50

    image-clef:
      network: resnet50
      is_center: False
      num_classes: 12
      bottleneck_dim: 1024
      iterations_per_epoch: 10

    visda:
      network: resnet50 # resnet101
      is_center: True # False
      num_classes: 12
      bottleneck_dim: 1024 # 2048
      iterations_per_epoch: 100

optimizer:
  init_lr: 0.001 # 0.004
  optim:
    type: sgd
    params:
      lr: 0.001 # 0.004
      momentum: 0.9
      weight_decay: 0.0005
      nesterov: True

  lr_scheduler:
    type: inv
    gamma: 0.001 # 0.0005
    decay_rate: 0.75 # 2.25

log:
  log_dir: 'logs'
  print_interval: 100
  log_image_interval: 1000
  num_embedding_samples: 384

train:
  max_iteration: 10000

